Feat: #17 attack state merge
SillyBusinessInc/SillyBusinessGame pull request #44
Opened 2024-11-11 14:17 UTC by SalaheddineZ

## Purpose of this PR:
Attack state, and that you can attack enemies with a slash of the tail

## How to test:
Press left mousebutton to attack

### links: 
[Ticket](https://github.com/SillyBusinessInc/SillyBusinessGame/issues/17)

2024-11-11 15:38 UTC, WantToBeeMe requested changes

2024-11-11 15:39 UTC, Isissss commented on Assets/Global/Scripts/Player/States/AttackingState.cs
> +    private bool isReturning;
very minor but id personally like to have these defined at the top

2024-11-11 15:39 UTC, Isissss commented on Assets/Global/Scripts/Player/Player.cs
general question, should we take an attack cooldown into account or no?

2024-11-11 15:41 UTC, Isissss commented on Assets/Global/Scripts/Player/States/AttackingState.cs
should this not be triggered once instead of in the fixedupdate? or am I misunderstanding?

2024-11-11 15:59 UTC, WantToBeeMe commented on Assets/Global/Scripts/Player/Player.cs
I think that is a good think to add to this

2024-11-13 11:12 UTC, WantToBeeMe approved these changes

2024-11-13 11:12 UTC, merged